#!/bin/sh
betterlockscreen -l() {
    i3betterlockscreen -l
}

case "$1" in
    betterlockscreen -l)
        betterlockscreen -l
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        betterlockscreen -l && systemctl suspend
        ;;
    hibernate)
        betterlockscreen -l && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {betterlockscreen -l|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
